### ISSUE TITLE
cURL Problem movie

### ISSUE THREAD

**Issue by aouniradouan** [betahut/movie-app#9]
in the first page it's show me this error : cURL error 6: Could not resolve host: movie (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by aouniradouan** [comment]
Can you reply please ?

**Comment by moaj257** [comment]
Hi @aouniradouan 
I am actually using a free account of heroku. Hope it works now at your end.

**Comment by aouniradouan** [comment]
> Hi @aouniradouan 
> I am actually using a free account of heroku. Hope it works now at your end.

I used it in my local server and there is a problem with it

**Comment by aouniradouan** [comment]
Illuminate\Http\Client\ConnectionException
cURL error 6: Could not resolve host: movie (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
https://one.chilya.com/moviez/public/

**Comment by moaj257** [comment]
> Illuminate\Http\Client\ConnectionException
> cURL error 6: Could not resolve host: movie (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
> https://one.chilya.com/moviez/public/


Add the following to your .env file

`TMDB_API_URL="https://api.themoviedb.org/3"`
`TMDB_BACKDROP_URL="https://image.tmdb.org/t/p/original"`
`TMDB_MEDIA_URL="https://image.tmdb.org/t/p/w780"`
`TMDB_NO_IMAGE_URL="/images/no-image.svg"`
`TMDB_POSTER_URL="https://image.tmdb.org/t/p/w500"`
`TMDB_PROFILE_URL="https://image.tmdb.org/t/p/w185"`
`TMDB_TOKEN="___YOUR_TMBD_TOKEN___"`

I hope this will fix the issue.

In your local laravel app structure , Open the file [`config/services.php`](https://github.com/betahut/movie-app/blob/master/config/services.php).

You will find all these environment variables.

And also open [`app/Http/Controllers/MoviesController.php`](https://github.com/betahut/movie-app/blob/master/app/Http/Controllers/MoviesController.php), You will find `config('services.tmdb.__***__')`, these were used from the file [`config/services.php`](https://github.com/betahut/movie-app/blob/master/config/services.php) in your local laravel app structure.

**Comment by aouniradouan** [comment]
> `TMDB_API_URL="https://api.themoviedb.org/3"`
> `TMDB_BACKDROP_URL="https://image.tmdb.org/t/p/original"`
> `TMDB_MEDIA_URL="https://image.tmdb.org/t/p/w780"`
> `TMDB_NO_IMAGE_URL="/images/no-image.svg"`
> `TMDB_POSTER_URL="https://image.tmdb.org/t/p/w500"`
> `TMDB_PROFILE_URL="https://image.tmdb.org/t/p/w185"`
> `TMDB_TOKEN="___YOUR_TMBD_TOKEN___"`

That very nice it work fine now but just css files is not loading how i can resolve this problem please

**Comment by moaj257** [comment]
I am not aware of what css issues you were facing.
Always try to upload a photo if possible.

**Comment by aouniradouan** [comment]
> I am not aware of what css issues you were facing.
> Always try to upload a photo if possible.

Check URL please and you will see : https://one.chilya.com/public/
Thank you :)

**Comment by aouniradouan** [comment]
> What kind of server are you using?
> Are you new to laravel hosting?
> 
> If your server does support htaccess, use the following for laravel web hosting
> 
> ```
> <IfModule mod_rewrite.c>
>     <IfModule mod_negotiation.c>
>         Options -MultiViews
>     </IfModule>
>     
>     RewriteEngine On
>     
>     RewriteCond %{REQUEST_FILENAME} -d [OR]
>     RewriteCond %{REQUEST_FILENAME} -f
>     RewriteRule ^ ^$1 [N]
> 
>     RewriteCond %{REQUEST_URI} (\.\w+$) [NC]
>     RewriteRule ^(.*)$ public/$1 
> 
>     RewriteCond %{REQUEST_FILENAME} !-d
>     RewriteCond %{REQUEST_FILENAME} !-f
>     RewriteRule ^ server.php
> 
> </IfModule>
> ```
> 
> Also use [`https://one.chilya.com/`](https://one.chilya.com) for to open the site and not [`https://one.chilya.com/public/`](https://one.chilya.com/public).

Thank You now every thing work fine <3
